### ISSUE TITLE
Add support for pulling datacite DOIs

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/orcid2vivo#4]
Currently can only pull crossref.

**Comment by justinlittman** [comment]
After further investigation, it was determined that datacite metadata records did not contain additional useful information.

For example:

```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-2.2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://datacite.org/schema/kernel-2.2
    http://schema.datacite.org/meta/kernel-2.2/metadata.xsd">
  <identifier identifierType="DOI">10.6083/M4MW2FFB</identifier>
  <creators>
    <creator>
      <creatorName>Wisdom, Jennifer P.</creatorName>
    </creator>
  </creators>
  <titles>
    <title>What teens need : barriers to seeking care for depression</title>
  </titles>
  <publisher>Oregon Health &amp; Science University</publisher>
  <publicationYear>2003</publicationYear>
  <resourceType resourceTypeGeneral="Text"/>
</resource>
```

**Comment by justinlittman** [comment]
Closing as won't fix.

**Comment by mconlon17** [comment]
Are there other resource types that might provide information for non-publications.  If DataCite has citations for data (for example) with a resource type of data, then perhaps the data fields for the resource type of data might form the basis for a data citation in VIVO.

**Comment by justinlittman** [comment]
Here's a link to the DataCite schemas:  https://schema.datacite.org/meta/kernel-3/index.html
